DEBUG    mytest:GraphqlClient.py:34 http://192.168.1.175:8888/graphql/?createThingInspection
DEBUG    mytest:GraphqlClient.py:35 {'Content-Type': 'application/json', 'authorization': 'Token eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJjcmVkZW50aWFscyI6eyJlbXBsb3llZV9pZCI6MSwiaXNfYWRtaW5fIjp0cnVlfSwidXNlciI6eyJpZCI6MSwiY29tcGFueV9pZCI6MSwibmFtZSI6Ilx1N2JhMVx1NzQwNlx1NTQ1OCIsImRlcGFydG1lbnRfaWQiOjEsImNvZGUiOm51bGwsInBob25lIjpudWxsLCJqb2IiOm51bGwsImVtYWlsIjpudWxsLCJhY2NvdW50IjoiYWRtaW4iLCJzdGF0dXMiOiJBQ1RJVkFURUQiLCJyb2xlcyI6bnVsbH0sImV4cCI6MTYwMDMxNDM0Mn0.UOI1OaH_ELEAVzSlldya-CY3ahODVdxWOAwKSCpjxGc'}
DEBUG    mytest:GraphqlClient.py:36 {
  'input': {
    'operator': {
      'id': 1,
    },
    'period': {
      'startAt': 1600227948628,
      'type': 'LIMITED',
    },
    'rule': {
      'id': 1,
    },
    'things': [
      {
        'id': 2,
      },
      {
        'id': 3,
      },
      {
        'id': 1,
      },
    ],
  },
}

ERROR    sgqlc.endpoint.http:base.py:213 GraphQL query failed with 1 errors
DEBUG    mytest:GraphqlClient.py:39 {
  'data': None,
  'errors': [
    {
      'extensions': {
        'code': 'USER_INPUT_ERROR',
      },
      'locations': [
        {
          'column': 5,
          'line': 2,
        },
      ],
      'message': '有限周期需要有结束时间',
      'path': ['createThingInspection'],
    },
  ],
}

DEBUG    mytest:AssertMethod.py:17 
jsonpath : '$..errors'
get
'[
  {
    'extensions': {
      'code': 'USER_INPUT_ERROR',
    },
    'locations': [
      {
        'column': 5,
        'line': 2,
      },
    ],
    'message': '有限周期需要有结束时间',
    'path': ['createThingInspection'],
  },
]
'
from
result
DEBUG    mytest:AssertMethod.py:18 except None